import type { PublicRepository } from "@worlddock/domain";

export const PUBLIC_REPOSITORIES: PublicRepository[] = [
  {
    id: "repo_tide",
    owner: "ren",
    slug: "tide-book",
    name: "潮汐之书",
    summary: "潮汐每 13 年一次反向，文明的法律、婚姻与税收都建立在这个循环之上。",
    readme: "一个把自然周期写进制度深处的海洋奇幻世界。",
    tags: ["海洋", "宗教", "制度"],
    stars: 184,
    forks: 23,
    seeds: 12,
    maturity: 72,
    updated: "3 小时前",
    version: "v1.2.0",
    visibility: "public",
    license: "free-fork-attribution",
    moderationStatus: "visible",
    moderationReason: null,
    releases: [
      {
        version: "v1.2.0",
        updated: "3 小时前",
        note: "新增潮税制度与两条高潜力故事种子。",
        addedSettings: 6,
        changedSettings: 2,
        removedSettings: 0,
        addedSeeds: 2,
        source: "cloud-publish",
      },
    ],
  },
  {
    id: "repo_ledger",
    owner: "lin",
    slug: "ledger-world",
    name: "账簿世界",
    summary: "所有人际关系都必须以双式记账法记录，未入账的承诺在法律上不存在。",
    readme: "一套由账本、债务和审计构成的蒸汽朋克社会。",
    tags: ["货币", "蒸汽", "审计"],
    stars: 92,
    forks: 11,
    seeds: 8,
    maturity: 54,
    updated: "昨天",
    version: "v0.8.0",
    visibility: "public",
    license: "non-commercial-attribution",
    moderationStatus: "visible",
    moderationReason: null,
    releases: [
      {
        version: "v0.8.0",
        updated: "昨天",
        note: "公开审计庭与债务婚姻设定。",
        addedSettings: 4,
        changedSettings: 1,
        removedSettings: 0,
        addedSeeds: 1,
        source: "local-push",
      },
    ],
  },
];
